# Generated by Django 4.0.6 on 2022-07-13 23:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='usefull_post',
        ),
        migrations.AddField(
            model_name='post',
            name='usefull_post',
            field=models.ManyToManyField(related_name='usefull_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
